[package]
name = "irc_hook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
irc = "0.15.0"
tokio = { version = "1.21.2", features = ["full"] }
futures = "0.3.24"